// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plpjzhmwcjcuvalebomk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBscGp6aG13Y2pjdXZhbGVib21rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3ODE2MzQsImV4cCI6MjA2NjM1NzYzNH0.W9Rsj8mNIWzSXf2p5xFn21EOyeHsobXQZndMg7lOfys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});